base:
  num_train_envs: 16
  n_rollout_threads: 16
  num_eval_envs: 8
  eval_episode_length: 200
  eval_interval: 50
  n_eval_rollout_threads: 8
  num_env_splits: 2

  episode_length: 400
  num_env_steps: 10.0e+6
  ppo_epoch: 10

  use_wandb: False
  wandb_project: sipowd-smac
  wandb_group: 2c64zg

  # seed should not be changed throughout iterations
  seed: 1
  seed_specify: True

  # diversity algorithm parameters
  use_filter: False
  use_gda: True
  use_cross_entropy: False
  n_iterations: 4
  threshold_eps: 3.0e-3
  ll_max: 10
  lagrangian_lr: 0.1
  discriminator_lr: 4.0e-4
  intrinsic_reward_scaling: 2.0
  warm_up_rate: 0.05
  # archive_policy_dirs:
  #   - results/smac/train/2010/iter0/models/model.pt
  # archive_traj_dirs:
  #   - results/smac/train/2010/iter0/models/data.traj

policy:
  type: wdpo
  args:
    hidden_dim: 64
    num_dense_layers: 2
    num_rnn_layers: 1
    discriminator_type: frame_stack
    discriminator_hidden_dim: 256

environment:
  type: smac
  args:
    base:
      map_name: 2c_vs_64zg
      frame_stack: True
      num_stack: 4
      stack_key: cent_state
