base:
  num_train_envs: 64
  n_rollout_threads: 32
  num_eval_envs: 16
  eval_episode_length: 100
  eval_interval: 50
  n_eval_rollout_threads: 16
  num_env_splits: 2

  episode_length: 150
  num_env_steps: 25.0e+6
  ppo_epoch: 10
  num_mini_batch: 2

  use_wandb: False
  wandb_project: sipowd-fb
  wandb_group: 3v1

  # seed should not be changed throughout iterations
  seed: 1
  seed_specify: True

  # diversity algorithm parameters
  use_filter: False
  use_gda: True
  use_cross_entropy: False
  n_iterations: 4
  threshold_eps: 2.0e-3
  ll_max: 10
  lagrangian_lr: 0.1
  discriminator_lr: 4.0e-4
  intrinsic_reward_scaling: 0.1
  warm_up_rate: 0.05
  # archive_policy_dirs:
  #   - results/sipo-wd/3v1/check/1/run1/iter0/model.pt
  #   - results/sipo-wd/3v1/check/1/run3/iter1/model.pt
  # archive_traj_dirs:
  #   - results/sipo-wd/3v1/check/1/run1/iter0/data.traj
  #   - results/sipo-wd/3v1/check/1/run3/iter1/data.traj

policy:
  type: wdpo
  args:
    hidden_dim: 64
    num_dense_layers: 2
    num_rnn_layers: 1
    discriminator_type: frame_stack
    discriminator_hidden_dim: 256


environment:
  type: football
  args:
    base:
      env_name: academy_3_vs_1_with_keeper
      share_reward: True
      frame_stack: True
      num_stack: 4
      stack_key: cent_state
    train:
      rewards: scoring,checkpoints
    eval:
      rewards: scoring
    render:
      rewards: scoring
      write_full_episode_dumps: True
      write_video: True
      logdir: results/football/render
      other_config_options:
        video_format: avi
        render_resolution_x: 960
        render_resolution_y: 540
        video_quality_level: 2
        display_game_stats: False