base:
  num_train_envs: 256
  n_rollout_threads: 32
  num_eval_envs: 32
  eval_episode_length: 100
  eval_interval: 50
  n_eval_rollout_threads: 8
  num_env_splits: 2

  episode_length: 50
  num_env_steps: 25.0e+6
  ppo_epoch: 4
  lr: 1.0e-3
  critic_lr: 1.0e-3

  use_wandb: False
  wandb_project: rkhs-mh
  wandb_group: mh
  wandb_name: mh-iter0

  # seed should not be changed throughout iterations
  seed: 1
  seed_specify: True

  # diversity algorithm parameters
  rbf_gamma: 1.0e-1 # if changed, threshold should be probably changed together
  threshold_eps: 5.66
  warmup_fraction: 0.05
  rkhs_action: False

  n_iterations: 8
  ll_max: 10.0
  lagrangian_lr: 0.01
  intrinsic_reward_scaling: 5.0e-2
  inherit_policy: False
  archive_policy_dirs:
      - results/monsterhunt/check/1/run6/iter0/models/model.pt
      - results/monsterhunt/check/1/run6/iter1/models/model.pt
      - results/monsterhunt/check/1/run6/iter2/models/model.pt
      - results/monsterhunt/check/1/run6/iter3/models/model.pt
      - results/monsterhunt/check/1/run6/iter4/models/model.pt
      - results/monsterhunt/check/1/run6/iter5/models/model.pt
      - results/monsterhunt/check/1/run6/iter6/models/model.pt
      - results/monsterhunt/check/1/run6/iter7/models/model.pt
  archive_traj_dirs:
      - results/monsterhunt/check/1/run6/iter0/models/data.traj
      - results/monsterhunt/check/1/run6/iter1/models/data.traj
      - results/monsterhunt/check/1/run6/iter2/models/data.traj
      - results/monsterhunt/check/1/run6/iter3/models/data.traj
      - results/monsterhunt/check/1/run6/iter4/models/data.traj
      - results/monsterhunt/check/1/run6/iter5/models/data.traj
      - results/monsterhunt/check/1/run6/iter6/models/data.traj
      - results/monsterhunt/check/1/run6/iter7/models/data.traj

policy:
  type: actor-critic
  args:
    hidden_dim: 64
    num_dense_layers: 2
    num_rnn_layers: 0

environment:
  type: staghunt
  args:
    base:
      env_name: StagHuntGW
      num_agents: 2
      episode_length: 50
      share_reward: False
      use_agent_id: True
      frame_stack: True
      num_stack: 4
      stack_key: discr_obs
      wrap_action: True
      length: 10