# cent state stack 4 = 184
base:
  num_train_envs: 64
  n_rollout_threads: 32
  num_eval_envs: 16
  eval_episode_length: 100
  eval_interval: 50
  n_eval_rollout_threads: 16
  num_env_splits: 2

  episode_length: 150
  num_env_steps: 100.0e+6
  ppo_epoch: 10
  num_mini_batch: 2

  use_wandb: False
  wandb_project: smerl-football
  wandb_group: ca-easy

  # seed should not be changed throughout iterations
  seed: 1
  seed_specify: True

  intrinsic_reward_scaling: 0.1
  smerl_threshold: 0.54

policy:
  type: smerl
  args:
    hidden_dim: 64
    num_dense_layers: 2
    num_rnn_layers: 1
    latent_dim: 4

environment:
  type: football
  args:
    base:
      env_name: academy_counterattack_easy
      share_reward: True
      frame_stack: True
      num_stack: 4
      stack_key: cent_state
      latent_dim: 4
      latent_concat_keys:
        - obs
    train:
      rewards: scoring,checkpoints
    eval:
      rewards: scoring
    render:
      rewards: scoring
      write_full_episode_dumps: True
      write_video: True
      logdir: results/football/render
      other_config_options:
        video_format: avi
        render_resolution_x: 960
        render_resolution_y: 540
        video_quality_level: 2
        display_game_stats: False
