# cent state 10
base:
  num_train_envs: 16
  n_rollout_threads: 16
  num_eval_envs: 8
  eval_episode_length: 200
  eval_interval: 50
  n_eval_rollout_threads: 8
  num_env_splits: 2

  episode_length: 400
  num_env_steps: 10.0e+6
  ppo_epoch: 10

  use_wandb: False
  wandb_project: rspo-smac
  wandb_group: 2c_64zg

  # seed should not be changed throughout iterations
  seed: 1
  seed_specify: True

  # diversity algorithm parameters
  threshold_annealing_schedule: linear
  use_reward_predictor: True
  auto_alpha: 0.3
  likelihood_alpha: 0.25
  likelihood_threshold: 10.0
  prediction_reward_alpha: 0.0
  exploration_reward_alpha: 5.0
  reward_prediction_multiplier: 1.0
  exploration_threshold: 0.6

  n_iterations: 4
  inherit_policy: False
  # archive_policy_dirs:
  #   - results/archive/smac/2_64/seed1/iter0/models/model.pt
    # - results/archive/smac/2_64/seed2/iter0/models/model.pt
    # - results/archive/smac/2_64/seed3/iter0/models/model.pt
  # archive_traj_dirs:
  #   - results/archive/smac/2_64/seed1/iter0/models/data.traj
    # - results/archive/smac/2_64/seed2/iter0/models/data.traj
    # - results/archive/smac/2_64/seed3/iter0/models/data.traj

policy:
  type: rspo
  args:
    hidden_dim: 64
    num_dense_layers: 2
    num_rnn_layers: 1

environment:
  type: smac
  args:
    base:
      map_name: 2c_vs_64zg
    eval:
      save_replay: False
      replay_dir: /home/fw/smac_replays_iclr2023/2c_vs_64zg/